// wagmi-disperse/src/components/TransactionSection.tsx
import type { Recipient, TokenInfo } from "../types";
import DisperseAddresses from "./DisperseAddresses";
import TransactionButton from "./TransactionButton";

interface TransactionSectionProps {
  sending: "ether" | "token" | null;
  recipients: Recipient[];
  token: TokenInfo;
  symbol: string;
  decimals: number;
  balance: bigint;
  leftAmount: bigint;
  totalAmount: bigint;
  disperseMessage?: string;
  chainId: number | undefined;
  verifiedAddress?: { address: `0x${string}`; label: string } | null;
  isContractDeployed: boolean;
  isBytecodeLoading: boolean;
  account?: `0x${string}`;
  nativeCurrencyName?: string;
  effectiveAllowance?: bigint;
}

export default function TransactionSection({
  sending,
  recipients,
  token,
  symbol,
  decimals,
  balance,
  leftAmount,
  totalAmount,
  disperseMessage,
  chainId,
  verifiedAddress,
  isContractDeployed,
  isBytecodeLoading,
  account,
  nativeCurrencyName = "ETH",
  effectiveAllowance = 0n,
}: TransactionSectionProps) {
  return (
    <>
      <section>
        <h2>confirm</h2>
        <DisperseAddresses
          recipients={recipients}
          symbol={symbol}
          decimals={decimals}
          balance={balance}
          left={leftAmount}
          total={totalAmount}
        />
        {sending === "ether" && (
          <TransactionButton
            show={true}
            disabled={leftAmount < 0n}
            title={`disperse ${nativeCurrencyName}`}
            action="disperseEther"
            message={disperseMessage}
            chainId={chainId}
            recipients={recipients}
            token={token}
            contractAddress={verifiedAddress?.address}
            isContractDeployed={isContractDeployed}
            isBytecodeLoading={isBytecodeLoading}
            account={account}
          />
        )}
      </section>

      {sending === "token" && (
        <div>
          <h2>allowance</h2>
          <p>
            {effectiveAllowance < totalAmount
              ? "allow smart contract to transfer tokens on your behalf."
              : "disperse contract has allowance, you can send tokens now."}
          </p>
          <TransactionButton
            title={effectiveAllowance < totalAmount ? "approve" : "revoke"}
            action={effectiveAllowance < totalAmount ? "approve" : "deny"}
            chainId={chainId}
            recipients={recipients}
            token={token}
            contractAddress={verifiedAddress?.address}
            isContractDeployed={isContractDeployed}
            isBytecodeLoading={isBytecodeLoading}
            className={effectiveAllowance >= totalAmount ? "secondary" : ""}
            account={account}
          />
          <TransactionButton
            show={true}
            disabled={leftAmount < 0n || effectiveAllowance < totalAmount}
            title="disperse token"
            action="disperseToken"
            message={disperseMessage}
            chainId={chainId}
            recipients={recipients}
            token={token}
            contractAddress={verifiedAddress?.address}
            isContractDeployed={isContractDeployed}
            isBytecodeLoading={isBytecodeLoading}
            account={account}
          />
        </div>
      )}
    </>
  );
}

// solid-disperse/src/components/TransactionSection.tsx
import { Show } from 'solid-js'
import type { Recipient, TokenInfo } from '../types'
import DisperseAddresses from './DisperseAddresses'
import TransactionButton from './TransactionButton'

interface TransactionSectionProps {
  sending: 'ether' | 'token' | null
  recipients: Recipient[]
  token: TokenInfo
  symbol: string
  decimals: number
  balance: bigint
  leftAmount: bigint
  totalAmount: bigint
  disperseMessage?: string
  chainId: number | undefined
  verifiedAddress?: { address: `0x${string}`; label: string } | null
  account?: `0x${string}`
  nativeCurrencyName?: string
  effectiveAllowance?: bigint
}

export default function TransactionSection(props: TransactionSectionProps) {
  const nativeCurrencyName = () => props.nativeCurrencyName || 'ETH'
  const effectiveAllowance = () => props.effectiveAllowance || 0n

  return (
    <>
      <section>
        <h2>confirm</h2>
        <DisperseAddresses
          recipients={props.recipients}
          symbol={props.symbol}
          decimals={props.decimals}
          balance={props.balance}
          left={props.leftAmount}
          total={props.totalAmount}
        />
        <Show when={props.sending === 'ether'}>
          <TransactionButton
            show={true}
            disabled={props.leftAmount < 0n}
            title={`disperse ${nativeCurrencyName()}`}
            action="disperseEther"
            message={props.disperseMessage}
            chainId={props.chainId}
            recipients={props.recipients}
            token={props.token}
            contractAddress={props.verifiedAddress?.address}
            account={props.account}
          />
        </Show>
      </section>

      <Show when={props.sending === 'token'}>
        <section>
          <h2>allowance</h2>
          <p>
            {effectiveAllowance() < props.totalAmount
              ? 'allow smart contract to transfer tokens on your behalf.'
              : 'disperse contract has allowance, you can send tokens now.'}
          </p>
          <TransactionButton
            title={effectiveAllowance() < props.totalAmount ? 'approve' : 'revoke'}
            action={effectiveAllowance() < props.totalAmount ? 'approve' : 'deny'}
            chainId={props.chainId}
            recipients={props.recipients}
            token={props.token}
            contractAddress={props.verifiedAddress?.address}
            class={effectiveAllowance() >= props.totalAmount ? 'secondary' : ''}
            account={props.account}
          />
          <TransactionButton
            show={true}
            disabled={props.leftAmount < 0n || effectiveAllowance() < props.totalAmount}
            title="disperse token"
            action="disperseToken"
            message={props.disperseMessage}
            chainId={props.chainId}
            recipients={props.recipients}
            token={props.token}
            contractAddress={props.verifiedAddress?.address}
            account={props.account}
          />
        </section>
      </Show>
    </>
  )
}
