// wagmi-disperse/src/App.tsx
import { useCallback, useMemo, useRef, useState } from "react";
import { formatUnits } from "viem";
import { useAccount, useBalance, useChainId, useConfig, useConnect } from "wagmi";

import { Suspense, lazy } from "react";
import CurrencySelector from "./components/CurrencySelector";
import Header from "./components/Header";
import NetworkStatus from "./components/NetworkStatus";
import RecipientInput from "./components/RecipientInput";
import TokenLoader from "./components/TokenLoader";
import TransactionSection from "./components/TransactionSection";
const DebugPanel = lazy(() => import("./components/debug/DebugPanel"));
import { AppState } from "./constants";
import { useAppState } from "./hooks/useAppState";
import { useContractVerification } from "./hooks/useContractVerification";
import { useCurrencySelection } from "./hooks/useCurrencySelection";
import { useTokenAllowance } from "./hooks/useTokenAllowance";
import type { Recipient, TokenInfo } from "./types";
import {
  getBalance,
  getDecimals,
  getDisperseMessage,
  getLeftAmount,
  getNativeCurrencyName,
  getSymbol,
  getTotalAmount,
} from "./utils/balanceCalculations";
import { canDeployToNetwork } from "./utils/contractVerify";
import { parseRecipients } from "./utils/parseRecipients";

function App() {
  const config = useConfig();
  const chainId = useChainId();
  const { address, status, isConnected } = useAccount();
  const { data: balanceData } = useBalance({
    address,
    chainId: chainId,
  });
  const { connectors, connect } = useConnect();

  const isChainSupported = chainId ? config.chains.some((chain) => chain.id === chainId) : false;
  const [customContractAddress, setCustomContractAddress] = useState<`0x${string}` | undefined>(undefined);

  const {
    verifiedAddress,
    hasContractAddress,
    isContractDeployed,
    isBytecodeLoading,
    potentialAddresses,
    createxDisperseAddress,
  } = useContractVerification(chainId, isConnected, customContractAddress);

  const canDeploy = canDeployToNetwork(chainId);

  const handleContractDeployed = useCallback((address: `0x${string}`) => {
    setCustomContractAddress(address);
  }, []);

  const [recipients, setRecipients] = useState<Recipient[]>([]);
  const walletStatus = status === "connected" ? `logged in as ${address}` : "please unlock wallet";
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const { sending, token, setSending, setToken } = useCurrencySelection();

  const { appState, setAppState } = useAppState({
    status,
    isConnected,
    chainId,
    isChainSupported,
    isContractDeployed,
    isBytecodeLoading,
    sending,
    token,
  });

  const parseAmounts = useCallback(() => {
    if (!textareaRef.current) return;

    const text = textareaRef.current.value;
    const decimals = getDecimals(sending, token);
    const newRecipients = parseRecipients(text, decimals);

    setRecipients(newRecipients);

    if (
      newRecipients.length &&
      (sending === "ether" || (sending === "token" && token.address && token.decimals !== undefined))
    ) {
      setAppState(AppState.ENTERED_AMOUNTS);
    }
  }, [sending, token, setAppState]);

  const handleRecipientsChange = useCallback(
    (newRecipients: Recipient[]) => {
      setRecipients(newRecipients);

      if (
        newRecipients.length &&
        (sending === "ether" || (sending === "token" && token.address && token.decimals !== undefined))
      ) {
        setAppState(AppState.ENTERED_AMOUNTS);
      }
    },
    [sending, token, setAppState],
  );

  const resetToken = useCallback(() => {
    setToken({});
    setAppState(AppState.CONNECTED_TO_WALLET);
  }, [setToken, setAppState]);

  const selectCurrency = useCallback(
    (type: "ether" | "token") => {
      setSending(type);

      if (type === "ether") {
        setAppState(AppState.SELECTED_CURRENCY);
        requestAnimationFrame(() => {
          if (textareaRef.current?.value) {
            parseAmounts();
          }
        });
      } else if (type === "token") {
        if (token.address && token.decimals !== undefined && token.symbol) {
          setAppState(AppState.SELECTED_CURRENCY);
          requestAnimationFrame(() => {
            if (textareaRef.current?.value) {
              parseAmounts();
            }
          });
        } else {
          resetToken();
        }
      }
    },
    [setSending, setAppState, token, parseAmounts, resetToken],
  );

  const selectToken = useCallback(
    (tokenInfo: TokenInfo) => {
      setToken(tokenInfo);
      setSending("token");
      setAppState(AppState.SELECTED_CURRENCY);

      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (textareaRef.current) {
            textareaRef.current.focus();
            if (tokenInfo.decimals !== undefined) {
              parseAmounts();
            }
          }
        });
      });
    },
    [setToken, setSending, setAppState, parseAmounts],
  );

  // Use reactive allowance hook
  const { allowance: currentAllowance } = useTokenAllowance({
    tokenAddress: token.address,
    account: address,
    spender: verifiedAddress?.address,
    chainId: chainId,
  });

  // Use the reactive allowance if available, otherwise fall back to the stored token allowance
  const effectiveAllowance = currentAllowance ?? token.allowance ?? 0n;

  // Memoize expensive calculations
  const totalAmount = useMemo(() => getTotalAmount(recipients), [recipients]);
  const balance = useMemo(() => getBalance(sending, token, balanceData), [sending, token, balanceData]);
  const leftAmount = useMemo(
    () => getLeftAmount(recipients, sending, token, balanceData),
    [recipients, sending, token, balanceData],
  );
  const disperseMessage = useMemo(
    () => getDisperseMessage(recipients, sending, { ...token, allowance: effectiveAllowance }, balanceData),
    [recipients, sending, token, effectiveAllowance, balanceData],
  );
  const symbol = useMemo(() => getSymbol(sending, token, chainId), [sending, token, chainId]);
  const decimals = useMemo(() => getDecimals(sending, token), [sending, token]);
  const nativeCurrencyName = useMemo(() => getNativeCurrencyName(chainId), [chainId]);

  // Display all wallet connectors
  const renderConnectors = () => {
    return (
      <div>
        {connectors.map((connector) => (
          <input
            key={connector.uid}
            type="submit"
            value={connector.name}
            onClick={() => connect({ connector })}
            style={{ marginRight: "10px", marginBottom: "10px" }}
          />
        ))}
      </div>
    );
  };

  return (
    <article>
      <Header chainId={chainId} address={address} />

      {appState === AppState.WALLET_REQUIRED && (
        <section>
          <h2>wallet required</h2>
          <p>non-ethereum browser, consider installing a wallet.</p>
        </section>
      )}

      {appState === AppState.NETWORK_UNAVAILABLE && (
        <NetworkStatus
          chainId={chainId}
          isBytecodeLoading={isBytecodeLoading}
          isContractDeployed={isContractDeployed}
          isConnected={isConnected}
          verifiedAddress={verifiedAddress}
          onContractDeployed={handleContractDeployed}
        />
      )}

      {appState >= AppState.UNLOCK_WALLET && !isConnected && (
        <section>
          <h2>connect to wallet</h2>
          <p>{renderConnectors()}</p>
          <p>{walletStatus}</p>
        </section>
      )}

      {appState >= AppState.CONNECTED_TO_WALLET && (
        <section>
          <CurrencySelector onSelect={selectCurrency} />
          {sending === "ether" && (
            <p>
              you have {formatUnits(balanceData?.value || 0n, 18)} {nativeCurrencyName}
              {balanceData?.value === 0n && chainId && <span className="warning">(make sure to add funds)</span>}
            </p>
          )}
        </section>
      )}

      {appState >= AppState.CONNECTED_TO_WALLET && sending === "token" && (
        <section>
          <TokenLoader
            onSelect={selectToken}
            onError={resetToken}
            chainId={chainId}
            account={address}
            token={token}
            contractAddress={verifiedAddress?.address}
          />
          {token.symbol && (
            <p className="mt">
              you have {formatUnits(token.balance || 0n, token.decimals || 18)} {token.symbol}
            </p>
          )}
        </section>
      )}

      {/* Show addresses input when:
          1. Ether is selected and we're connected to a supported wallet/network, or
          2. We're in SELECTED_CURRENCY state or higher (any currency),
          3. Token is selected and we have a valid token (with symbol)
          BUT never show when on an unsupported network (NETWORK_UNAVAILABLE state)
      */}
      {appState !== AppState.NETWORK_UNAVAILABLE &&
        ((appState >= AppState.CONNECTED_TO_WALLET && sending === "ether") ||
          appState >= AppState.SELECTED_CURRENCY ||
          (sending === "token" && !!token.symbol)) && (
          <RecipientInput
            sending={sending}
            token={token}
            onRecipientsChange={handleRecipientsChange}
            textareaRef={textareaRef}
          />
        )}

      {appState >= AppState.ENTERED_AMOUNTS && (
        <TransactionSection
          sending={sending}
          recipients={recipients}
          token={token}
          symbol={symbol}
          decimals={decimals}
          balance={balance}
          leftAmount={leftAmount}
          totalAmount={totalAmount}
          disperseMessage={disperseMessage}
          chainId={chainId}
          verifiedAddress={verifiedAddress}
          isContractDeployed={isContractDeployed}
          isBytecodeLoading={isBytecodeLoading}
          account={address}
          nativeCurrencyName={nativeCurrencyName}
          effectiveAllowance={effectiveAllowance}
        />
      )}

      {/* Debug Panel */}
      <Suspense fallback={null}>
        <DebugPanel
          appState={appState}
          chainId={chainId}
          isChainSupported={isChainSupported}
          hasContractAddress={hasContractAddress}
          customContractAddress={customContractAddress}
          isContractDeployed={isContractDeployed}
          isBytecodeLoading={isBytecodeLoading}
          verifiedAddress={verifiedAddress}
          canDeploy={canDeploy}
          createxDisperseAddress={createxDisperseAddress}
          potentialAddresses={potentialAddresses}
          sending={sending}
          isConnected={isConnected}
          tokenSymbol={token?.symbol}
          recipientsCount={recipients.length}
        />
      </Suspense>
    </article>
  );
}

export default App;

// solid-disperse/src/App.tsx
import { createSignal, createMemo, createResource, Show, For, Switch, Match, onMount, onCleanup } from 'solid-js'
import { connect, getBalance } from '@wagmi/core'
import { formatUnits } from 'viem'
import { config } from './wagmi.config'
import { account, chainId, isConnected, initWeb3Watchers } from './web3.store'
import { chains, nativeCurrencyName } from './networks'
import { useContractVerification } from './hooks/useContractVerification'
import { useTokenAllowance } from './hooks/useTokenAllowance'
import { useAppState } from './hooks/useAppState'
import { AppState } from './constants'
import Header from './components/Header'
import Footer from './components/Footer'
import CurrencySelector from './components/CurrencySelector'
import TokenLoader from './components/TokenLoader'
import RecipientInput from './components/RecipientInput'
import TransactionSection from './components/TransactionSection'
import NetworkStatus from './components/NetworkStatus'
import {
  getTotalAmount,
  getBalance as getBalanceUtil,
  getLeftAmount,
  getDisperseMessage,
  getSymbol,
  getDecimals,
} from './utils'
import type { Recipient, TokenInfo } from './types'

function App() {
  // Initialize Web3 watchers
  onMount(() => {
    const cleanup = initWeb3Watchers()
    onCleanup(cleanup)
  })

  // Local state signals
  const [sending, setSending] = createSignal<'ether' | 'token'>('ether')
  const [token, setToken] = createSignal<TokenInfo>({})
  const [recipients, setRecipients] = createSignal<Recipient[]>([])

  // Computed values
  const isChainSupported = createMemo(() => {
    const id = chainId()
    return id ? chains.some((chain) => chain.id === id) : false
  })

  // Contract verification
  const { verifiedAddress, isLoading: isContractLoading, isContractDeployed, contractStatuses } = useContractVerification(
    chainId,
    isConnected
  )

  // App state management
  const { appState, isReady } = useAppState({
    isConnected,
    chainId,
    isChainSupported,
    isContractDeployed,
    isContractLoading,
    sending,
    token,
    recipients,
  })

  // Fetch ETH balance
  const [balanceData] = createResource(
    () => ({ address: account().address, chainId: chainId() }),
    async ({ address, chainId }) => {
      if (!address || !chainId) return null
      try {
        return await getBalance(config, { address, chainId })
      } catch {
        return null
      }
    }
  )

  // Token allowance
  const { allowance: currentAllowance, refetch: refetchAllowance } = useTokenAllowance({
    tokenAddress: () => token().address,
    account: () => account().address,
    spender: () => verifiedAddress()?.address,
    chainId,
  })

  // Connect handlers
  const handleConnect = async (connector: any) => {
    try {
      await connect(config, { connector })
    } catch (error) {
      console.error('Failed to connect:', error)
    }
  }

  // Render wallet connectors
  const renderConnectors = () => (
    <div>
      <For each={config.connectors}>
        {(connector) => (
          <input
            type="submit"
            value={connector.name}
            onClick={() => handleConnect(connector)}
            style={{ 'margin-right': '10px', 'margin-bottom': '10px' }}
          />
        )}
      </For>
    </div>
  )

  return (
    <article>
      <Header chainId={chainId()} address={account().address} />

      <Switch>
        <Match when={appState() === AppState.WALLET_REQUIRED}>
          <section>
            <h2>connect to wallet</h2>
            <p>{renderConnectors()}</p>
          </section>
        </Match>

        <Match when={appState() === AppState.NETWORK_UNSUPPORTED}>
          <section>
            <h2>Unsupported Network</h2>
            <p>Please switch to a supported network.</p>
          </section>
        </Match>

        <Match when={appState() === AppState.CONTRACT_LOADING}>
          <section>
            <h2>Checking Contract</h2>
            <p class="pending">Verifying disperse contract on this network...</p>
          </section>
        </Match>

        <Match when={appState() === AppState.CONTRACT_NOT_DEPLOYED}>
          <NetworkStatus
            chainId={chainId()}
            isBytecodeLoading={isContractLoading()}
            isContractDeployed={isContractDeployed()}
            isConnected={isConnected()}
            verifiedAddress={verifiedAddress()}
          />
        </Match>

        <Match when={isReady()}>
          <Show when={verifiedAddress()}>
            <section class="contract-info">
              <p class="sc">Using {verifiedAddress()!.label} disperse contract</p>
            </section>
          </Show>
          
          <section>
            <CurrencySelector onSelect={setSending} />
            <Show when={sending() === 'ether'}>
              <p>
                you have {balanceData()?.value ? formatUnits(balanceData()!.value, 18) : '0'} {nativeCurrencyName(chainId())}
                <Show when={balanceData()?.value === 0n && chainId()}>
                  <span class="warning"> (make sure to add funds)</span>
                </Show>
              </p>
            </Show>
          </section>
          
          <Show when={sending() === 'token'}>
            <section>
              <TokenLoader
                onSelect={setToken}
                onError={() => setSending('ether')}
                chainId={chainId()}
                account={account().address}
                token={token()}
                contractAddress={verifiedAddress()?.address}
              />
              <Show when={token().symbol}>
                <p class="mt">
                  you have {token().balance ? formatUnits(token().balance || 0n, token().decimals || 18) : '0'} {token().symbol}
                </p>
              </Show>
            </section>
          </Show>
          
          <Show when={sending() === 'ether' || (sending() === 'token' && token().symbol)}>
            <RecipientInput
              sending={sending()}
              token={token()}
              onRecipientsChange={setRecipients}
            />
          </Show>
          
          <Show when={recipients().length > 0}>
            {(() => {
              const totalAmount = getTotalAmount(recipients())
              const balance = getBalanceUtil(sending(), token(), balanceData() || undefined)
              const leftAmount = getLeftAmount(recipients(), sending(), token(), balanceData() || undefined)
              const disperseMessage = getDisperseMessage(recipients(), sending(), token(), balanceData() || undefined)
              const symbol = getSymbol(sending(), token(), chainId())
              const decimals = getDecimals(sending(), token())
              const nativeCurrency = nativeCurrencyName(chainId())
              
              return (
                <TransactionSection
                  sending={sending()}
                  recipients={recipients()}
                  token={token()}
                  symbol={symbol}
                  decimals={decimals}
                  balance={balance}
                  leftAmount={leftAmount}
                  totalAmount={totalAmount}
                  disperseMessage={disperseMessage}
                  chainId={chainId()}
                  verifiedAddress={verifiedAddress()}
                  account={account().address}
                  nativeCurrencyName={nativeCurrency}
                  effectiveAllowance={currentAllowance() ?? token().allowance}
                  onAllowanceChange={refetchAllowance}
                />
              )
            })()}
          </Show>
        </Match>
      </Switch>
      
      <Footer chainId={chainId()} verifiedAddress={verifiedAddress()} contractStatuses={contractStatuses()} />
    </article>
  )
}

export default App
