// wagmi-disperse/src/main.tsx
import { Buffer } from 'buffer'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { WagmiProvider } from 'wagmi'

import App from './App.tsx'
import { config } from './wagmi.ts'

import './css/normalize.css'
import './css/tufte.css'
import './css/disperse.css'

globalThis.Buffer = Buffer

const queryClient = new QueryClient()

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </WagmiProvider>
  </React.StrictMode>,
)

// solid-disperse/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import { ErrorBoundary } from 'solid-js'
import './index.css'
import './css/normalize.css'
import './css/tufte.css'
import './css/disperse.css'
import App from './App.tsx'

const root = document.getElementById('root')

render(() => <App />, root!)
